### ISSUE TITLE
Variety of enabled payment methods

### ISSUE THREAD

**Issue by nickfarrow** [SatSale/SatSale#48]
There should be greater choice of payment method configuration

```
config.pay_method = [bitcoind,  clightning, pseudonode]
```

What is the logic for default payment method? (Could be order in list!)

Are other methods displayed as options on payment page?

Payment processors:
```
lnd = {
    name: "lnd",
    domain_path: "/cln/", #sets route domain
    ...
   onchain: False,
}
```

**Comment by kristapsk** [comment]
Agree, current way of "lnd"/"clightning" meaning "lnd+bitcoind"/"clightning+bitcoind" and "bitcoind" meaning just "bitcoind", isn't intuitive.

Backend node and getting invoices / addresses config also could be split. With #36 it would make sense to have zpub address derivation in bitcoind mode and in that case you have bitcoind backend but different wallet choices - bitcoind wallet or external zpub.

Another thing is that sideshift itself could be a "payment method". In weak hands mode it could just ask LN invoice for SideShift directly. Benefits are two: 1) you are sure user will get error instead of invoice if SideShift is down, 2) if I host such instance on my servers, I don't become payment processor, as bitcoins at any point isn't processed by my LN node. It's less regulation from legal perspective if you are just IT service provider, not payment processor.
